services:
  db:
    image: rapidfort/microsoft-sql-server-2019-ib:latest
    environment:
      - SA_PASSWORD=!fgvHiringProcess2025
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_HTTPS_CERTIFICATE_PATH=/https/aspnetcore.crt
      - ASPNETCORE_HTTPS_CERTIFICATE_PASSWORD=fgvHiringProcess2025
